remote_theme: just-the-docs/just-the-docs
title: "Portfolio Ángel MR – Technical Docs"
description: "Guía técnica de la página web de Ángel Martín Ramírez."
baseurl: "/Portfolio"
color_scheme: dark
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"