remote_theme: just-the-docs/just-the-docs
title: "Selfhosted Home Server – Technical Docs"
description: "Guía técnica del HomeLab personal de Ángel Martín Ramírez: contenedores, automatización, IA y más."
baseurl: "/selfhosted-homeserver-documentation"
color_scheme: dark
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"